services:
  random-image:
    image: huohen92/random-image-server:v0.02
    container_name: random-image
    ports:
      - "5566:5566"
    volumes:
      - ./images:/app/images
      - ./public:/app/public
    restart: unless-stopped
